apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hackathon-equipe9
  namespace: argocd
spec:
  description: >-
    Projet Argo CD - Hackathon OVHcloud x Ynov (Equipe 9).
    Chaine d'audit et de remediation GitOps securisee sur Kubernetes.
  sourceRepos:
    - "https://github.com/maxfrn65/YnovXOVH.git"
    - "https://kyverno.github.io/kyverno/"
    - "https://falcosecurity.github.io/charts"
    - "https://aquasecurity.github.io/helm-charts/"
    - "https://prometheus-community.github.io/helm-charts"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
