apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-webapp
  namespace: vulnerable-demo
  labels:
    app: legacy-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-webapp
  template:
    metadata:
      labels:
        app: legacy-webapp
    spec:
      containers:
        - name: webapp
          image: <nouvelle_image_sécurisée>
          securityContext:
            privileged: false
            runAsUser: 10001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities: {}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: host-root
              mountPath: /var/www/html
      volumes:
        - name: host-root
          hostPath:
            path: /var/www/html
